"""
Views for the Projects app.

Permission matrix:
  - LIST / RETRIEVE  → anyone (IsAuthenticatedOrReadOnly default)
  - CREATE / UPDATE / DELETE → authenticated admin users only
"""

from rest_framework import status, viewsets, filters
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny
from rest_framework.response import Response
from django_filters.rest_framework import DjangoFilterBackend

from .models import Project
from .serializers import ProjectSerializer, ProjectListSerializer
from portfolio_backend.permissions import IsAdminOrReadOnly


class ProjectViewSet(viewsets.ModelViewSet):
    """
    ViewSet providing full CRUD for portfolio projects.

    Endpoints generated by the router:
        GET     /api/projects/          → list (paginated)
        POST    /api/projects/          → create (admin only)
        GET     /api/projects/{id}/     → retrieve
        PUT     /api/projects/{id}/     → update (admin only)
        PATCH   /api/projects/{id}/     → partial update (admin only)
        DELETE  /api/projects/{id}/     → destroy (admin only)
    """

    queryset = Project.objects.all()
    permission_classes = [IsAdminOrReadOnly]
    filter_backends = [DjangoFilterBackend, filters.SearchFilter, filters.OrderingFilter]
    search_fields = ["title", "description", "tech_stack"]
    ordering_fields = ["created_at", "title"]
    ordering = ["-created_at"]

    def get_serializer_class(self):
        """Return a lightweight serializer for list actions."""
        if self.action == "list":
            return ProjectListSerializer
        return ProjectSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(
            {"message": "Project created successfully.", "data": serializer.data},
            status=status.HTTP_201_CREATED,
            headers=headers,
        )

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        return Response(
            {"message": "Project updated successfully.", "data": serializer.data},
            status=status.HTTP_200_OK,
        )

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return Response(
            {"message": "Project deleted successfully."},
            status=status.HTTP_200_OK,
        )
